# Generated by Django 3.0.8 on 2020-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WeFund', max_length=100)),
                ('description', models.CharField(default='Just a website', max_length=500)),
                ('address', models.CharField(default='Algiers', max_length=100)),
                ('logo', models.CharField(default='We are here to help', max_length=200)),
                ('email', models.EmailField(default='taha@gmail.com', max_length=100)),
                ('phone_number', models.IntegerField(default='000112121231')),
            ],
        ),
    ]
