# Generated by Django 3.0.8 on 2020-10-25 17:41

from django.db import migrations, models
import sitecomponents.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecomponents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='image',
            field=models.ImageField(upload_to=sitecomponents.models.upload_location),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
