# Generated by Django 3.0.8 on 2020-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecomponents', '0002_auto_20201025_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wefund',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
