# Generated by Django 3.0.8 on 2020-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecomponents', '0003_auto_20201025_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wefund',
            name='logo',
            field=models.URLField(default='hi.com/hi'),
            preserve_default=False,
        ),
    ]
